version: '3.1'

services:
  springboot:
   
    build: .
    restart: always
    container_name: QuestionGeneratorContainer
    ports:
      - 8080:8080
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    container_name: mongocontainer
    ports:  
      - 27017:27017
    volumes:
      - /var/lib/mongodb:/var/lib/mongodb
     # - $HOME/data/restaurant-bkp:/data/bkp
    restart: always
    command: mongod 
